import logging
from typing import List, Optional
from openai import OpenAI, APIConnectionError, RateLimitError, AuthenticationError
from config import OPENAI_API_KEY, OPENAI_BASE_URL, DEFAULT_LLM_MODEL, LLM_TEMPERATURE

logger = logging.getLogger(__name__)


class Generator:
    def __init__(self, model: str = DEFAULT_LLM_MODEL, api_key: Optional[str] = None, base_url: Optional[str] = None):
        self.model = model
        self.api_key = api_key or OPENAI_API_KEY
        self.base_url = base_url or OPENAI_BASE_URL
        client_kwargs = {"api_key": self.api_key}
        if self.base_url:
            client_kwargs["base_url"] = self.base_url
        self.client = OpenAI(**client_kwargs)

    def generate_answer(self, query: str, context_chunks: List[str], temperature: float = LLM_TEMPERATURE) -> str:
        if not self.api_key:
            return "Error: OPENAI_API_KEY is missing."
        if not context_chunks:
            return "I don't have enough data to answer that."

        context_text = "\n---\n".join(context_chunks)
        prompt = f"""Answer the question ONLY using the provided context.
If the answer is not in the context, say: 'I don't have enough data to answer that.'

CONTEXT:
{context_text}

QUESTION:
{query}

ANSWER:"""

        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": "You are a professional AI Career Advisor."},
                    {"role": "user", "content": prompt}
                ],
                temperature=temperature
            )
            return response.choices[0].message.content.strip()
        except AuthenticationError:
            return "Error: Invalid OpenAI API key."
        except RateLimitError:
            return "Error: OpenAI rate limit reached."
        except APIConnectionError:
            return "Error: Failed to connect to OpenAI API."
        except Exception as e:
            return f"Error generating answer: {e}"


class LocalAdvisor:
    def __init__(self):
        pass

    def generate_answer(self, query: str, context_chunks: List[str], max_chunks: int = 3) -> str:
        if not context_chunks:
            return "I don't have enough data in my local knowledge base to answer that."
        summary = "Based on my semantic search, here are the key facts:\n"
        for chunk in context_chunks[:max_chunks]:
            summary += f"• {chunk}\n"
        summary += "\n[Note: This answer was generated by the LocalAdvisor fallback.]"
        return summary


if __name__ == "__main__":
    advisor = LocalAdvisor()
    mock_context = [
        "In 2024, a Data Scientist in New York earns $150,000.",
        "Senior Data Scientists can earn up to $200,000."
    ]
    answer = advisor.generate_answer("How much does a Data Scientist make?", mock_context)
    print(f"LocalAdvisor Answer:\n{answer}")
