from abc import ABC, abstractmethod
from typing import List, Optional
import google.generativeai as genai
from config import (
    DEFAULT_LLM_MODEL, LLM_TEMPERATURE, 
    GEMINI_API_KEY
)

import logging
logger = logging.getLogger(__name__)


class GenerationError(Exception):
    """Raised when LLM generation fails."""
    pass


class BaseGenerator(ABC):
    @abstractmethod
    def generate_answer(self, query: str, context_chunks: List[str], **kwargs) -> str:
        pass


class GeminiGenerator(BaseGenerator):

    def __init__(self, model: str, api_key: str) -> None:
        self.model = model
        genai.configure(api_key=api_key)
        self.gemini_model = genai.GenerativeModel(self.model)
        logger.info(f"Initialized Gemini model: {self.model}")

    def generate_answer(self, query: str, context_chunks: List[str], temperature: float = LLM_TEMPERATURE) -> str:
        if not context_chunks:
            return "I don't have enough data to answer that."

        context_text = "\n---\n".join(context_chunks)
        prompt = f"""Answer the question ONLY using the provided context.
If the answer is not in the context, say: 'I don't have enough data to answer that.'

CONTEXT:
{context_text}

QUESTION:
{query}

ANSWER:"""

        try:
            response = self.gemini_model.generate_content(
                prompt,
                generation_config=genai.types.GenerationConfig(temperature=temperature)
            )
            return response.text.strip()
        except Exception as e:
            logger.exception("Error during Gemini generation")
            raise GenerationError(f"Gemini generation failed: {e}") from e


class Generator(BaseGenerator):

    def __init__(self, model: str = DEFAULT_LLM_MODEL, api_key: Optional[str] = None) -> None:
        key = api_key or GEMINI_API_KEY
        if not key:
            logger.error("GEMINI_API_KEY is missing")
            raise ValueError("GEMINI_API_KEY is required")
            
        self._impl = GeminiGenerator(model, key)

    def generate_answer(self, query: str, context_chunks: List[str], **kwargs) -> str:
        return self._impl.generate_answer(query, context_chunks, **kwargs)


class LocalAdvisor(BaseGenerator):

    def generate_answer(self, query: str, context_chunks: List[str], max_chunks: int = 3, **kwargs) -> str:
        if not context_chunks:
            return "I don't have enough data in my local knowledge base to answer that."
            
        summary = "Based on my semantic search, here are the key facts:\n"
        for chunk in context_chunks[:max_chunks]:
            summary += f"• {chunk}\n"
        summary += "\n[Note: This answer was generated by the LocalAdvisor fallback.]"
        return summary


if __name__ == "__main__":
    advisor = LocalAdvisor()
    mock_context = [
        "In 2024, a Data Scientist in New York earns $150,000.",
        "Senior Data Scientists can earn up to $200,000."
    ]
    answer = advisor.generate_answer("How much does a Data Scientist make?", mock_context)
    print(f"LocalAdvisor Answer:\n{answer}")
